package sagiri.personal.facade.vo;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The vo of the table "t_web_address_category".
 * @author Kahle
 * @date 2021-02-26T11:04:49.714+0800
 */
@Data
public class WebAddressCategoryVO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 网址分类ID
     */
    private Long id;
    /**
     * 父分类ID
     */
    private Long parentId;
    /**
     * 分类名称
     */
    private String name;
    /**
     * 分类描述
     */
    private String description;
    /**
     * 排序
     */
    private Integer sort;
    /**
     * 创建者ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 更新者ID
     */
    private String updaterId;
    /**
     * 更新时间
     */
    private Date updateTime;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-02-26T11:04:50.365+0800. */

}
