package sagiri.content.service.dto;

import artoria.common.Paging;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_article".
 * @author Kahle
 * @date 2020-12-01T15:05:13.823+0800
 */
@Data
public class ArticleDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 文章ID
     */
    private Long id;
    /**
     * 文章标题
     */
    private String title;
    /**
     * 自定义访问路径
     */
    private String slug;
    /**
     * 文章类型
     */
    private Integer type;
    /**
     * 作者ID
     */
    private String authorId;
    /**
     * 缩略图
     */
    private String thumbnail;
    /**
     * 文章格式
     */
    private String format;
    /**
     * 文章内容
     */
    private String content;
    /**
     * 文章来源
     */
    private String origin;
    /**
     * 发布时间
     */
    private Date releaseTime;
    /**
     * 状态：0 草稿，1 发布
     */
    private Integer status;
    /**
     * 创建者ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-12-01T15:05:14.478+0800. */

    /**
     * 允许Feed：0 不允许，1 允许
     */
    private Integer allowFeed;
    /**
     * 允许Ping：0 不允许，1 允许
     */
    private Integer allowPing;
    /**
     * 允许评论：0 不允许，1 允许
     */
    private Integer allowComment;
    /**
     * 文章分类
     */
    private String categories;
    /**
     * 文章标签
     */
    private String tags;
    /**
     * 分页参数
     */
    @JsonUnwrapped
    private Paging paging;

}
