package sagiri.content.service.dto;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_article_relation".
 * @author Kahle
 * @date 2021-03-05T10:23:44.708+0800
 */
@Data
public class ArticleRelationDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 关系ID
     */
    private Long id;
    /**
     * 文章ID
     */
    private Long articleId;
    /**
     * 关系类型
     */
    private Integer type;
    /**
     * 目标ID
     */
    private Long targetId;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-03-05T10:23:45.817+0800. */

}
