package sagiri.system.facade.vo;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The vo of the table "t_event_record".
 * @author Kahle
 * @date 2020-09-15T10:55:27.628+0800
 */
@Data
public class EventRecordVO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 事件记录ID
     */
    private Long id;
    /**
     * 事件名称
     */
    private String eventName;
    /**
     * 事件类型
     */
    private String eventType;
    /**
     * 事件时间
     */
    private Date eventTime;
    /**
     * 明显的ID
     */
    private String distinctId;
    /**
     * 匿名的ID
     */
    private String anonymousId;
    /**
     * 客户端的ID
     */
    private String clientId;
    /**
     * 客户端的应用的ID
     */
    private String clientAppId;
    /**
     * 客户端的设备的ID
     */
    private String clientDeviceId;
    /**
     * 客户端的用户代理
     */
    private String clientUserAgent;
    /**
     * 客户端的网络地址
     */
    private String clientNetAddress;
    /**
     * 被访问的接口的ID
     */
    private String interfaceId;
    /**
     * 服务器的ID
     */
    private String serverId;
    /**
     * 服务器的应用的ID
     */
    private String serverAppId;
    /**
     * 属性JSON
     */
    private String propertiesJson;
    /**
     * 创建人ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 更新人ID
     */
    private String updaterId;
    /**
     * 更新时间
     */
    private Date updateTime;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-09-15T10:55:32.900+0800. */

}
