package sagiri.core.service.dto;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_article".
 * @author Kahle
 * @date 2020-12-01T15:05:13.823+0800
 */
@Data
public class ArticleDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 文章ID
     */
    private String id;
    /**
     * 文章的数字ID
     */
    private Long numberId;
    /**
     * 文章标题
     */
    private String title;
    /**
     * 文章类型
     */
    private Integer type;
    /**
     * 文章分类
     */
    private String category;
    /**
     * 作者ID
     */
    private String authorId;
    /**
     * 作者名称
     */
    private String authorName;
    /**
     * 文章内容
     */
    private String content;
    /**
     * 文章来源
     */
    private String origin;
    /**
     * 状态：0 草稿，1 发布
     */
    private Integer status;
    /**
     * 发布时间
     */
    private Date releaseTime;
    /**
     * 创建者ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2020-12-01T15:05:14.478+0800. */

}
