package sagiri.content.facade.vo;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The vo of the table "t_article_relation".
 * @author Kahle
 * @date 2021-03-05T10:23:44.708+0800
 */
@Data
public class ArticleRelationVO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 关系ID
     */
    private Long id;
    /**
     * 文章ID
     */
    private Long articleId;
    /**
     * 关系类型
     */
    private Integer type;
    /**
     * 目标ID
     */
    private Long targetId;
    /**
     * 创建者ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 更新者ID
     */
    private String updaterId;
    /**
     * 更新时间
     */
    private Date updateTime;
    /**
     * 数据状态
     */
    private Integer aliveFlag;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-03-05T10:23:45.850+0800. */

}
